name: GH Pages build master branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build
      - run: git checkout gh-pages
      # Command soup:
      - run: echo "::set-output name=STATUS::$(git status --porcelain)"
        id: status
      - run: git add -A
        if: ${{ steps.status.outputs.STATUS != "" }}
      - run: git commit -m "Build"
        if: ${{ steps.status.outputs.STATUS != "" }}
      - run: git push
        if: ${{ steps.status.outputs.STATUS != "" }}
      
      
    
